title: Nepal Online School
year: 2020
email: nepalonlineschool@gmail.com
description: >-
  Nepal Online School(NOS) is a non-profit digital learning platform working for free education in Nepal.
  With dedicated and hardworking mentors, we have created quality videos from academics to yoga.
baseurl: ""
url: "https://nepalonlineschool.org"
image_base_url: /assets/

future: true

repo: "https://github.com/nepal-online-school/website"
github_user: "nepal-online-school"
github_repo: "website"

links:
  - title: Facebook
    url: https://www.facebook.com/NepalOnlineSchool/
    icon: fab fa-facebook-f
  - title: YouTube Channel
    url: https://www.youtube.com/channel/UClDw4ijXzb9YxiU5nWinEfQ
    icon: fab fa-youtube
  - title: Telegram
    url: https://t.me/nepalonlineschool
    icon: fab fa-telegram
  - title: Instagram
    url: https://www.instagram.com/nepalonlineschoolnonprofit/
    icon: fab fa-instagram
  - title: LinkedIn
    url: https://www.linkedin.com/in/nepalonlineschool-non-profit-project/
    icon: fab fa-linkedin

google_analytics: # your google analytics id
# Disqus Comments
disqus:
  shortname: # disqus short name

logo_pixels: 34
color: "#6d161e"
# color: "#8c1515" # primary color for header, buttons

# Build settings
markdown: kramdown

# If you add tags to pages, define this variable to link them to some external search
# If you want to link to tags locally on the site, leave this commented out
# tag_search_endpoint: https://ask.cyberinfrastructure.org/search?q=
tag_color: primary # danger, success, warning, primary, info, secondary

accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
